# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u540d\u5b57')),
                ('introduction', models.TextField(max_length=400, verbose_name='\u5f71\u97f3\u7b80\u4ecb')),
                ('cover_image', models.ImageField(default='images/default.jpeg', upload_to='images/movie/', verbose_name='\u6d77\u62a5\u5c01\u9762\uff08\u56fe\u7247\uff09')),
                ('comment', models.TextField(max_length=40, verbose_name='\u4e2a\u4eba\u8bc4\u8bba')),
                ('director', models.CharField(max_length=50, verbose_name='\u5bfc\u6f14')),
                ('type', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u7c7b\u578b')),
                ('release_time', models.CharField(max_length=20, verbose_name='\u4e0a\u6620\u65f6\u95f4')),
                ('starring', models.CharField(max_length=50, verbose_name='\u4e3b\u6f14')),
                ('production_cost', models.CharField(max_length=20, verbose_name='\u5236\u7247\u6210\u672c')),
                ('filming_location', models.CharField(max_length=20, verbose_name='\u62cd\u6444\u5730\u70b9')),
                ('film_length', models.CharField(max_length=10, verbose_name='\u7247\u957f')),
            ],
            options={
                'verbose_name': '\u7535\u5f71',
                'verbose_name_plural': '\u7535\u5f71',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6b4c\u66f2\u540d\u5b57')),
                ('singer', models.CharField(max_length=50, verbose_name='\u6f14\u5531\u8005')),
                ('original_author', models.CharField(max_length=50, verbose_name='\u6b4c\u66f2\u539f\u5531')),
                ('cover_image', models.ImageField(default='images/default.jpeg', upload_to='images/music/', verbose_name='\u6d77\u62a5\u5c01\u9762\uff08\u56fe\u7247\uff09')),
                ('song', models.FileField(default='media/default.mp3', upload_to='media/', verbose_name='\u6b4c\u66f2')),
                ('album', models.CharField(max_length=50, verbose_name='\u6240\u5c5e\u4e13\u8f91')),
                ('language', models.CharField(max_length=50, verbose_name='\u6b4c\u66f2\u8bed\u8a00')),
                ('music_style', models.CharField(max_length=20, verbose_name='\u97f3\u4e50\u98ce\u683c')),
                ('lyrics', models.TextField(verbose_name='\u6b4c\u8bcd')),
                ('lyricswriter', models.CharField(max_length=50, verbose_name='\u586b\u8bcd')),
                ('songwriter', models.CharField(max_length=50, verbose_name='\u586b\u66f2')),
                ('song_length', models.CharField(max_length=10, verbose_name='\u6b4c\u66f2\u65f6\u957f')),
                ('wonderful_lyrics', models.TextField(max_length=50, verbose_name='\u7cbe\u5f69\u6b4c\u8bcd')),
            ],
        ),
    ]
